#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
################# WARNING ####################
##############################################
###
### This file is auto generated by the resource
###   module builder playbook.
###
### Do not edit this file manually.
###
### Changes to this file will be over written
###   by the resource module builder.
###
### Changes should be made in the model used to
###   generate this file or in the resource module
###   builder template.
###
##############################################
##############################################
##############################################
"""
The arg spec for the ios_interfaces module
"""

class L2_InterfacesArgs(object):

    def __init__(self, **kwargs):
        pass

    access_arg_spec = dict(vlan=dict(type=str, required=True))
    trunk_arg_spec = dict(allowed_vlan=dict(type=list, required=True),
                          encapsulation=dict(type=str),
                          native_vlan=dict(type=str),
                          pruning_vlan=dict(type=list)
                          )

    config_spec = {
        'name': dict(type='str', required=True),
        'access': dict(type=list, element=dict, options=access_arg_spec),
        'trunk': dict(element=dict, type=list, options=trunk_arg_spec)
    }

    argument_spec = {
        'state': dict(default='merged', choices=['merged', 'replaced', 'overridden', 'deleted']),
        'config': dict(type='list', elements='dict', options=config_spec)
    }

