#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat Inc.
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
################# WARNING ####################
##############################################
###
### This file is auto generated by the resource
###   module builder playbook.
###
### Do not edit this file manually.
###
### Changes to this file will be over written
###   by the resource module builder.
###
### Changes should be made in the model used to
###   generate this file or in the resource module
###   builder template.
###
##############################################
##############################################
##############################################
"""
The arg spec for the iosxr_l2_interfaces module
"""

class L2_InterfacesArgs(object):

    def __init__(self, **kwargs):
        pass

    l2_protocol_arg_spec = dict(cdp=dict(type=str, element=dict, choices=['drop','forward', 'tunnel']),
                                pvst=dict(type=str, element=dict, choices=['drop','forward', 'tunnel']),
                                stp=dict(type=str, element=dict, choices=['drop','forward', 'tunnel']),
                                vtp=dict(type=str, element=dict, choices=['drop','forward', 'tunnel'])
                                )

    config_spec = {
        'name': dict(type='str', required=True),
        'native_vlan': dict(type=str),
        'l2transport': dict(element=dict, type=bool),
        'l2protocol': dict(element=dict, type=list, options=l2_protocol_arg_spec),
        'q_vlan':dict(element=dict, type=list),
        'propagate': dict(element=dict, type=bool)
    }

    argument_spec = {
        'state': dict(default='merged', choices=['merged', 'replaced', 'overridden', 'deleted']),
        'config': dict(type='list', elements='dict', options=config_spec)
    }
