#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat Inc.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
#############################################
#                WARNING
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
# generate this file or in the resource module
# builder template.
#
##############################################
"""
The arg spec for the ios_l3_interfaces module
"""


class L3_InterfacesArgs(object):

    def __init__(self, **kwargs):
        pass

    ipv4addr_spec = dict(address=dict(type=str),
                         secondary=dict(type=bool, default=True),
                         dhcp_client=dict(type=str),
                         dhcp_hostname=dict(type=str))

    ipv6addr_spec = dict(address=dict(type=str),
                         autoconfig=dict(type=bool),
                         dhcp=dict(type=bool))

    config_spec = {
        'name': dict(type='str', required=True),
        'ipv4': dict(type='list', elements='dict', options=ipv4addr_spec),
        'ipv6': dict(type='list', elements='dict', options=ipv6addr_spec)
    }

    argument_spec = {
        'state': dict(default='merged', choices=['merged', 'replaced', 'overridden', 'deleted']),
        'config': dict(type='list', elements='dict', options=config_spec)
    }
