#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2019 Red Hat
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
################# WARNING ####################
##############################################
###
### This file is auto generated by the resource
###   module builder playbook.
###
### Do not edit this file manually.
###
### Changes to this file will be over written
###   by the resource module builder.
###
### Changes should be made in the model used to
###   generate this file or in the resource module
###   builder template.
###
##############################################
##############################################
##############################################
"""
The arg spec for the vyos_interfaces module
"""

class InterfacesArgs(object): #pylint: disable=R0903
    """The arg spec for the vyos_interfaces module
    """

    def __init__(self, **kwargs):
        pass

    argument_spec = {u'state': {'default': u'merged', 'required': False, 'type': u'str', 'choices': [u'merged', u'replaced', u'overridden', u'deleted']}, u'config': {'elements': u'dict', 'type': 'list', 'options': {u'enable': {'default': True, 'required': False, 'type': u'bool'}, u'description': {'required': False, 'type': u'str'}, u'duplex': {'required': False, 'type': u'str', 'choices': [u'full', u'half', u'auto']}, u'mtu': {'required': False, 'type': u'str'}, u'speed': {'required': False, 'type': u'str', 'choices': [u'auto', u'10', u'100', u'1000', u'2500', u'10000']}, u'name': {'required': False, 'type': u'str'}}}} #pylint: disable=C0301
